# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/oozgur/Desktop/c++/cs32/minirogue/minirogue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/oozgur/Desktop/c++/cs32/minirogue/minirogue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oozgur/Desktop/c++/cs32/minirogue/minirogue/CMakeFiles /Users/oozgur/Desktop/c++/cs32/minirogue/minirogue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oozgur/Desktop/c++/cs32/minirogue/minirogue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minirogue

# Build rule for target.
minirogue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minirogue
.PHONY : minirogue

# fast build rule for target.
minirogue/fast:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/build
.PHONY : minirogue/fast

Actor.o: Actor.cpp.o

.PHONY : Actor.o

# target to build an object file
Actor.cpp.o:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/Actor.cpp.o
.PHONY : Actor.cpp.o

Actor.i: Actor.cpp.i

.PHONY : Actor.i

# target to preprocess a source file
Actor.cpp.i:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/Actor.cpp.i
.PHONY : Actor.cpp.i

Actor.s: Actor.cpp.s

.PHONY : Actor.s

# target to generate assembly for a file
Actor.cpp.s:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/Actor.cpp.s
.PHONY : Actor.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/Game.cpp.s
.PHONY : Game.cpp.s

GameObject.o: GameObject.cpp.o

.PHONY : GameObject.o

# target to build an object file
GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/GameObject.cpp.o
.PHONY : GameObject.cpp.o

GameObject.i: GameObject.cpp.i

.PHONY : GameObject.i

# target to preprocess a source file
GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/GameObject.cpp.i
.PHONY : GameObject.cpp.i

GameObject.s: GameObject.cpp.s

.PHONY : GameObject.s

# target to generate assembly for a file
GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/GameObject.cpp.s
.PHONY : GameObject.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/main.cpp.s
.PHONY : main.cpp.s

utilities.o: utilities.cpp.o

.PHONY : utilities.o

# target to build an object file
utilities.cpp.o:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/utilities.cpp.o
.PHONY : utilities.cpp.o

utilities.i: utilities.cpp.i

.PHONY : utilities.i

# target to preprocess a source file
utilities.cpp.i:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/utilities.cpp.i
.PHONY : utilities.cpp.i

utilities.s: utilities.cpp.s

.PHONY : utilities.s

# target to generate assembly for a file
utilities.cpp.s:
	$(MAKE) -f CMakeFiles/minirogue.dir/build.make CMakeFiles/minirogue.dir/utilities.cpp.s
.PHONY : utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... minirogue"
	@echo "... Actor.o"
	@echo "... Actor.i"
	@echo "... Actor.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... GameObject.o"
	@echo "... GameObject.i"
	@echo "... GameObject.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

